/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareerResourcesRouteImport } from './routes/career-resources'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JobSeekerRouteImport } from './routes/job-seeker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedEmployerRouteRouteImport } from './routes/_authenticated/employer/route'
import { Route as AuthenticatedJobSeekerRouteRouteImport } from './routes/_authenticated/job-seeker/route'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesCompanySlugRouteImport } from './routes/companies.$companySlug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin/applications'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin/jobs'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer/index'
import { Route as AuthenticatedEmployerApplicationsRouteImport } from './routes/_authenticated/employer/applications'
import { Route as AuthenticatedEmployerCandidatesRouteImport } from './routes/_authenticated/employer/candidates'
import { Route as AuthenticatedEmployerCompanyRouteImport } from './routes/_authenticated/employer/company'
import { Route as AuthenticatedEmployerInterviewsRouteImport } from './routes/_authenticated/employer/interviews'
import { Route as AuthenticatedEmployerMessagesRouteImport } from './routes/_authenticated/employer/messages'
import { Route as AuthenticatedEmployerNotificationsRouteImport } from './routes/_authenticated/employer/notifications'
import { Route as AuthenticatedEmployerPostJobRouteImport } from './routes/_authenticated/employer/post-job'
import { Route as AuthenticatedEmployerSettingsRouteImport } from './routes/_authenticated/employer/settings'
import { Route as AuthenticatedJobSeekerIndexRouteImport } from './routes/_authenticated/job-seeker/index'
import { Route as AuthenticatedJobSeekerApplicationsRouteImport } from './routes/_authenticated/job-seeker/applications'
import { Route as AuthenticatedJobSeekerInterviewsRouteImport } from './routes/_authenticated/job-seeker/interviews'
import { Route as AuthenticatedJobSeekerMessagesRouteImport } from './routes/_authenticated/job-seeker/messages'
import { Route as AuthenticatedJobSeekerNotificationsRouteImport } from './routes/_authenticated/job-seeker/notifications'
import { Route as AuthenticatedJobSeekerProfileRouteImport } from './routes/_authenticated/job-seeker/profile'
import { Route as AuthenticatedJobSeekerRecommendedJobsRouteImport } from './routes/_authenticated/job-seeker/recommended-jobs'
import { Route as AuthenticatedJobSeekerResumesRouteImport } from './routes/_authenticated/job-seeker/resumes'
import { Route as AuthenticatedJobSeekerSavedJobsRouteImport } from './routes/_authenticated/job-seeker/saved-jobs'
import { Route as AuthenticatedJobSeekerSettingsRouteImport } from './routes/_authenticated/job-seeker/settings'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs.$jobId_.apply'
import { Route as AuthenticatedAdminCompaniesCompanyIdRouteImport } from './routes/_authenticated/admin/companies_.$companyId'
import { Route as AuthenticatedAdminReportsReportIdRouteImport } from './routes/_authenticated/admin/reports_.$reportId'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users_.$userId'
import { Route as AuthenticatedEmployerApplicationsApplicationIdRouteImport } from './routes/_authenticated/employer/applications_.$applicationId'
import { Route as AuthenticatedEmployerCandidatesCandidateIdRouteImport } from './routes/_authenticated/employer/candidates_.$candidateId'
import { Route as AuthenticatedEmployerJobsIndexRouteImport } from './routes/_authenticated/employer/jobs.index'
import { Route as AuthenticatedJobSeekerApplicationsApplicationIdRouteImport } from './routes/_authenticated/job-seeker/applications_.$applicationId'
import { Route as AuthenticatedEmployerJobsJobIdEditRouteImport } from './routes/_authenticated/employer/jobs.$jobId.edit'
import { Route as AuthenticatedEmployerJobsJobIdMatchesRouteImport } from './routes/_authenticated/employer/jobs.$jobId_.matches'
import { Route as AuthenticatedEmployerJobsJobIdPipelineRouteImport } from './routes/_authenticated/employer/jobs.$jobId_.pipeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerResourcesRoute = CareerResourcesRouteImport.update({
  id: '/career-resources',
  path: '/career-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerRoute = JobSeekerRouteImport.update({
  id: '/job-seeker',
  path: '/job-seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerRouteRoute =
  AuthenticatedEmployerRouteRouteImport.update({
    id: '/employer',
    path: '/employer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobSeekerRouteRoute =
  AuthenticatedJobSeekerRouteRouteImport.update({
    id: '/job-seeker',
    path: '/job-seeker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanySlugRoute = CompaniesCompanySlugRouteImport.update({
  id: '/companies/$companySlug',
  path: '/companies/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerApplicationsRoute =
  AuthenticatedEmployerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerCandidatesRoute =
  AuthenticatedEmployerCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerCompanyRoute =
  AuthenticatedEmployerCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerInterviewsRoute =
  AuthenticatedEmployerInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerMessagesRoute =
  AuthenticatedEmployerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerNotificationsRoute =
  AuthenticatedEmployerNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerPostJobRoute =
  AuthenticatedEmployerPostJobRouteImport.update({
    id: '/post-job',
    path: '/post-job',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerSettingsRoute =
  AuthenticatedEmployerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedJobSeekerIndexRoute =
  AuthenticatedJobSeekerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerApplicationsRoute =
  AuthenticatedJobSeekerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerInterviewsRoute =
  AuthenticatedJobSeekerInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerMessagesRoute =
  AuthenticatedJobSeekerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerNotificationsRoute =
  AuthenticatedJobSeekerNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerProfileRoute =
  AuthenticatedJobSeekerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerRecommendedJobsRoute =
  AuthenticatedJobSeekerRecommendedJobsRouteImport.update({
    id: '/recommended-jobs',
    path: '/recommended-jobs',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerResumesRoute =
  AuthenticatedJobSeekerResumesRouteImport.update({
    id: '/resumes',
    path: '/resumes',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerSavedJobsRoute =
  AuthenticatedJobSeekerSavedJobsRouteImport.update({
    id: '/saved-jobs',
    path: '/saved-jobs',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedJobSeekerSettingsRoute =
  AuthenticatedJobSeekerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/jobs/$jobId_/apply',
  path: '/jobs/$jobId/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCompaniesCompanyIdRoute =
  AuthenticatedAdminCompaniesCompanyIdRouteImport.update({
    id: '/companies_/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsReportIdRoute =
  AuthenticatedAdminReportsReportIdRouteImport.update({
    id: '/reports_/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users_/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedEmployerApplicationsApplicationIdRoute =
  AuthenticatedEmployerApplicationsApplicationIdRouteImport.update({
    id: '/applications_/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerCandidatesCandidateIdRoute =
  AuthenticatedEmployerCandidatesCandidateIdRouteImport.update({
    id: '/candidates_/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerJobsIndexRoute =
  AuthenticatedEmployerJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedJobSeekerApplicationsApplicationIdRoute =
  AuthenticatedJobSeekerApplicationsApplicationIdRouteImport.update({
    id: '/applications_/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthenticatedJobSeekerRouteRoute,
  } as any)
const AuthenticatedEmployerJobsJobIdEditRoute =
  AuthenticatedEmployerJobsJobIdEditRouteImport.update({
    id: '/jobs/$jobId/edit',
    path: '/jobs/$jobId/edit',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerJobsJobIdMatchesRoute =
  AuthenticatedEmployerJobsJobIdMatchesRouteImport.update({
    id: '/jobs/$jobId_/matches',
    path: '/jobs/$jobId/matches',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)
const AuthenticatedEmployerJobsJobIdPipelineRoute =
  AuthenticatedEmployerJobsJobIdPipelineRouteImport.update({
    id: '/jobs/$jobId_/pipeline',
    path: '/jobs/$jobId/pipeline',
    getParentRoute: () => AuthenticatedEmployerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-resources': typeof CareerResourcesRoute
  '/contact': typeof ContactRoute
  '/employer': typeof AuthenticatedEmployerRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/job-seeker': typeof AuthenticatedJobSeekerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/companies/$companySlug': typeof CompaniesCompanySlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/employer/candidates': typeof AuthenticatedEmployerCandidatesRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/employer/notifications': typeof AuthenticatedEmployerNotificationsRoute
  '/employer/post-job': typeof AuthenticatedEmployerPostJobRoute
  '/employer/settings': typeof AuthenticatedEmployerSettingsRoute
  '/job-seeker/applications': typeof AuthenticatedJobSeekerApplicationsRoute
  '/job-seeker/interviews': typeof AuthenticatedJobSeekerInterviewsRoute
  '/job-seeker/messages': typeof AuthenticatedJobSeekerMessagesRoute
  '/job-seeker/notifications': typeof AuthenticatedJobSeekerNotificationsRoute
  '/job-seeker/profile': typeof AuthenticatedJobSeekerProfileRoute
  '/job-seeker/recommended-jobs': typeof AuthenticatedJobSeekerRecommendedJobsRoute
  '/job-seeker/resumes': typeof AuthenticatedJobSeekerResumesRoute
  '/job-seeker/saved-jobs': typeof AuthenticatedJobSeekerSavedJobsRoute
  '/job-seeker/settings': typeof AuthenticatedJobSeekerSettingsRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/job-seeker/': typeof AuthenticatedJobSeekerIndexRoute
  '/admin/companies/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/admin/reports/$reportId': typeof AuthenticatedAdminReportsReportIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/employer/applications/$applicationId': typeof AuthenticatedEmployerApplicationsApplicationIdRoute
  '/employer/candidates/$candidateId': typeof AuthenticatedEmployerCandidatesCandidateIdRoute
  '/job-seeker/applications/$applicationId': typeof AuthenticatedJobSeekerApplicationsApplicationIdRoute
  '/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/employer/jobs/$jobId/edit': typeof AuthenticatedEmployerJobsJobIdEditRoute
  '/employer/jobs/$jobId/matches': typeof AuthenticatedEmployerJobsJobIdMatchesRoute
  '/employer/jobs/$jobId/pipeline': typeof AuthenticatedEmployerJobsJobIdPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-resources': typeof CareerResourcesRoute
  '/contact': typeof ContactRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/job-seeker': typeof AuthenticatedJobSeekerIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/companies/$companySlug': typeof CompaniesCompanySlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/employer/candidates': typeof AuthenticatedEmployerCandidatesRoute
  '/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/employer/notifications': typeof AuthenticatedEmployerNotificationsRoute
  '/employer/post-job': typeof AuthenticatedEmployerPostJobRoute
  '/employer/settings': typeof AuthenticatedEmployerSettingsRoute
  '/job-seeker/applications': typeof AuthenticatedJobSeekerApplicationsRoute
  '/job-seeker/interviews': typeof AuthenticatedJobSeekerInterviewsRoute
  '/job-seeker/messages': typeof AuthenticatedJobSeekerMessagesRoute
  '/job-seeker/notifications': typeof AuthenticatedJobSeekerNotificationsRoute
  '/job-seeker/profile': typeof AuthenticatedJobSeekerProfileRoute
  '/job-seeker/recommended-jobs': typeof AuthenticatedJobSeekerRecommendedJobsRoute
  '/job-seeker/resumes': typeof AuthenticatedJobSeekerResumesRoute
  '/job-seeker/saved-jobs': typeof AuthenticatedJobSeekerSavedJobsRoute
  '/job-seeker/settings': typeof AuthenticatedJobSeekerSettingsRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/companies/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/admin/reports/$reportId': typeof AuthenticatedAdminReportsReportIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/employer/applications/$applicationId': typeof AuthenticatedEmployerApplicationsApplicationIdRoute
  '/employer/candidates/$candidateId': typeof AuthenticatedEmployerCandidatesCandidateIdRoute
  '/job-seeker/applications/$applicationId': typeof AuthenticatedJobSeekerApplicationsApplicationIdRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsIndexRoute
  '/employer/jobs/$jobId/edit': typeof AuthenticatedEmployerJobsJobIdEditRoute
  '/employer/jobs/$jobId/matches': typeof AuthenticatedEmployerJobsJobIdMatchesRoute
  '/employer/jobs/$jobId/pipeline': typeof AuthenticatedEmployerJobsJobIdPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/career-resources': typeof CareerResourcesRoute
  '/contact': typeof ContactRoute
  '/employer': typeof EmployerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/job-seeker': typeof JobSeekerRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteRouteWithChildren
  '/_authenticated/job-seeker': typeof AuthenticatedJobSeekerRouteRouteWithChildren
  '/companies/$companySlug': typeof CompaniesCompanySlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/employer/applications': typeof AuthenticatedEmployerApplicationsRoute
  '/_authenticated/employer/candidates': typeof AuthenticatedEmployerCandidatesRoute
  '/_authenticated/employer/company': typeof AuthenticatedEmployerCompanyRoute
  '/_authenticated/employer/interviews': typeof AuthenticatedEmployerInterviewsRoute
  '/_authenticated/employer/messages': typeof AuthenticatedEmployerMessagesRoute
  '/_authenticated/employer/notifications': typeof AuthenticatedEmployerNotificationsRoute
  '/_authenticated/employer/post-job': typeof AuthenticatedEmployerPostJobRoute
  '/_authenticated/employer/settings': typeof AuthenticatedEmployerSettingsRoute
  '/_authenticated/job-seeker/applications': typeof AuthenticatedJobSeekerApplicationsRoute
  '/_authenticated/job-seeker/interviews': typeof AuthenticatedJobSeekerInterviewsRoute
  '/_authenticated/job-seeker/messages': typeof AuthenticatedJobSeekerMessagesRoute
  '/_authenticated/job-seeker/notifications': typeof AuthenticatedJobSeekerNotificationsRoute
  '/_authenticated/job-seeker/profile': typeof AuthenticatedJobSeekerProfileRoute
  '/_authenticated/job-seeker/recommended-jobs': typeof AuthenticatedJobSeekerRecommendedJobsRoute
  '/_authenticated/job-seeker/resumes': typeof AuthenticatedJobSeekerResumesRoute
  '/_authenticated/job-seeker/saved-jobs': typeof AuthenticatedJobSeekerSavedJobsRoute
  '/_authenticated/job-seeker/settings': typeof AuthenticatedJobSeekerSettingsRoute
  '/jobs/$jobId_/apply': typeof JobsJobIdApplyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/job-seeker/': typeof AuthenticatedJobSeekerIndexRoute
  '/_authenticated/admin/companies_/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/_authenticated/admin/reports_/$reportId': typeof AuthenticatedAdminReportsReportIdRoute
  '/_authenticated/admin/users_/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/employer/applications_/$applicationId': typeof AuthenticatedEmployerApplicationsApplicationIdRoute
  '/_authenticated/employer/candidates_/$candidateId': typeof AuthenticatedEmployerCandidatesCandidateIdRoute
  '/_authenticated/job-seeker/applications_/$applicationId': typeof AuthenticatedJobSeekerApplicationsApplicationIdRoute
  '/_authenticated/employer/jobs/': typeof AuthenticatedEmployerJobsIndexRoute
  '/_authenticated/employer/jobs/$jobId/edit': typeof AuthenticatedEmployerJobsJobIdEditRoute
  '/_authenticated/employer/jobs/$jobId_/matches': typeof AuthenticatedEmployerJobsJobIdMatchesRoute
  '/_authenticated/employer/jobs/$jobId_/pipeline': typeof AuthenticatedEmployerJobsJobIdPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career-resources'
    | '/contact'
    | '/employer'
    | '/forgot-password'
    | '/job-seeker'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/companies/$companySlug'
    | '/jobs/$jobId'
    | '/companies/'
    | '/jobs/'
    | '/admin/applications'
    | '/admin/audit-logs'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/reports'
    | '/admin/users'
    | '/employer/applications'
    | '/employer/candidates'
    | '/employer/company'
    | '/employer/interviews'
    | '/employer/messages'
    | '/employer/notifications'
    | '/employer/post-job'
    | '/employer/settings'
    | '/job-seeker/applications'
    | '/job-seeker/interviews'
    | '/job-seeker/messages'
    | '/job-seeker/notifications'
    | '/job-seeker/profile'
    | '/job-seeker/recommended-jobs'
    | '/job-seeker/resumes'
    | '/job-seeker/saved-jobs'
    | '/job-seeker/settings'
    | '/jobs/$jobId/apply'
    | '/admin/'
    | '/employer/'
    | '/job-seeker/'
    | '/admin/companies/$companyId'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/employer/applications/$applicationId'
    | '/employer/candidates/$candidateId'
    | '/job-seeker/applications/$applicationId'
    | '/employer/jobs/'
    | '/employer/jobs/$jobId/edit'
    | '/employer/jobs/$jobId/matches'
    | '/employer/jobs/$jobId/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career-resources'
    | '/contact'
    | '/employer'
    | '/forgot-password'
    | '/job-seeker'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/companies/$companySlug'
    | '/jobs/$jobId'
    | '/companies'
    | '/jobs'
    | '/admin/applications'
    | '/admin/audit-logs'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/reports'
    | '/admin/users'
    | '/employer/applications'
    | '/employer/candidates'
    | '/employer/company'
    | '/employer/interviews'
    | '/employer/messages'
    | '/employer/notifications'
    | '/employer/post-job'
    | '/employer/settings'
    | '/job-seeker/applications'
    | '/job-seeker/interviews'
    | '/job-seeker/messages'
    | '/job-seeker/notifications'
    | '/job-seeker/profile'
    | '/job-seeker/recommended-jobs'
    | '/job-seeker/resumes'
    | '/job-seeker/saved-jobs'
    | '/job-seeker/settings'
    | '/jobs/$jobId/apply'
    | '/admin'
    | '/admin/companies/$companyId'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/employer/applications/$applicationId'
    | '/employer/candidates/$candidateId'
    | '/job-seeker/applications/$applicationId'
    | '/employer/jobs'
    | '/employer/jobs/$jobId/edit'
    | '/employer/jobs/$jobId/matches'
    | '/employer/jobs/$jobId/pipeline'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/career-resources'
    | '/contact'
    | '/employer'
    | '/forgot-password'
    | '/job-seeker'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/employer'
    | '/_authenticated/job-seeker'
    | '/companies/$companySlug'
    | '/jobs/$jobId'
    | '/companies/'
    | '/jobs/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/employer/applications'
    | '/_authenticated/employer/candidates'
    | '/_authenticated/employer/company'
    | '/_authenticated/employer/interviews'
    | '/_authenticated/employer/messages'
    | '/_authenticated/employer/notifications'
    | '/_authenticated/employer/post-job'
    | '/_authenticated/employer/settings'
    | '/_authenticated/job-seeker/applications'
    | '/_authenticated/job-seeker/interviews'
    | '/_authenticated/job-seeker/messages'
    | '/_authenticated/job-seeker/notifications'
    | '/_authenticated/job-seeker/profile'
    | '/_authenticated/job-seeker/recommended-jobs'
    | '/_authenticated/job-seeker/resumes'
    | '/_authenticated/job-seeker/saved-jobs'
    | '/_authenticated/job-seeker/settings'
    | '/jobs/$jobId_/apply'
    | '/_authenticated/admin/'
    | '/_authenticated/employer/'
    | '/_authenticated/job-seeker/'
    | '/_authenticated/admin/companies_/$companyId'
    | '/_authenticated/admin/reports_/$reportId'
    | '/_authenticated/admin/users_/$userId'
    | '/_authenticated/employer/applications_/$applicationId'
    | '/_authenticated/employer/candidates_/$candidateId'
    | '/_authenticated/job-seeker/applications_/$applicationId'
    | '/_authenticated/employer/jobs/'
    | '/_authenticated/employer/jobs/$jobId/edit'
    | '/_authenticated/employer/jobs/$jobId_/matches'
    | '/_authenticated/employer/jobs/$jobId_/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CareerResourcesRoute: typeof CareerResourcesRoute
  ContactRoute: typeof ContactRoute
  EmployerRoute: typeof EmployerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobSeekerRoute: typeof JobSeekerRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  CompaniesCompanySlugRoute: typeof CompaniesCompanySlugRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-resources': {
      id: '/career-resources'
      path: '/career-resources'
      fullPath: '/career-resources'
      preLoaderRoute: typeof CareerResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker': {
      id: '/job-seeker'
      path: '/job-seeker'
      fullPath: '/job-seeker'
      preLoaderRoute: typeof JobSeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-seeker': {
      id: '/_authenticated/job-seeker'
      path: '/job-seeker'
      fullPath: '/job-seeker'
      preLoaderRoute: typeof AuthenticatedJobSeekerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companySlug': {
      id: '/companies/$companySlug'
      path: '/companies/$companySlug'
      fullPath: '/companies/$companySlug'
      preLoaderRoute: typeof CompaniesCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/applications': {
      id: '/_authenticated/employer/applications'
      path: '/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof AuthenticatedEmployerApplicationsRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/candidates': {
      id: '/_authenticated/employer/candidates'
      path: '/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof AuthenticatedEmployerCandidatesRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/company': {
      id: '/_authenticated/employer/company'
      path: '/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof AuthenticatedEmployerCompanyRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/interviews': {
      id: '/_authenticated/employer/interviews'
      path: '/interviews'
      fullPath: '/employer/interviews'
      preLoaderRoute: typeof AuthenticatedEmployerInterviewsRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/messages': {
      id: '/_authenticated/employer/messages'
      path: '/messages'
      fullPath: '/employer/messages'
      preLoaderRoute: typeof AuthenticatedEmployerMessagesRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/notifications': {
      id: '/_authenticated/employer/notifications'
      path: '/notifications'
      fullPath: '/employer/notifications'
      preLoaderRoute: typeof AuthenticatedEmployerNotificationsRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/post-job': {
      id: '/_authenticated/employer/post-job'
      path: '/post-job'
      fullPath: '/employer/post-job'
      preLoaderRoute: typeof AuthenticatedEmployerPostJobRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/settings': {
      id: '/_authenticated/employer/settings'
      path: '/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof AuthenticatedEmployerSettingsRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/job-seeker/': {
      id: '/_authenticated/job-seeker/'
      path: '/'
      fullPath: '/job-seeker/'
      preLoaderRoute: typeof AuthenticatedJobSeekerIndexRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/applications': {
      id: '/_authenticated/job-seeker/applications'
      path: '/applications'
      fullPath: '/job-seeker/applications'
      preLoaderRoute: typeof AuthenticatedJobSeekerApplicationsRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/interviews': {
      id: '/_authenticated/job-seeker/interviews'
      path: '/interviews'
      fullPath: '/job-seeker/interviews'
      preLoaderRoute: typeof AuthenticatedJobSeekerInterviewsRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/messages': {
      id: '/_authenticated/job-seeker/messages'
      path: '/messages'
      fullPath: '/job-seeker/messages'
      preLoaderRoute: typeof AuthenticatedJobSeekerMessagesRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/notifications': {
      id: '/_authenticated/job-seeker/notifications'
      path: '/notifications'
      fullPath: '/job-seeker/notifications'
      preLoaderRoute: typeof AuthenticatedJobSeekerNotificationsRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/profile': {
      id: '/_authenticated/job-seeker/profile'
      path: '/profile'
      fullPath: '/job-seeker/profile'
      preLoaderRoute: typeof AuthenticatedJobSeekerProfileRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/recommended-jobs': {
      id: '/_authenticated/job-seeker/recommended-jobs'
      path: '/recommended-jobs'
      fullPath: '/job-seeker/recommended-jobs'
      preLoaderRoute: typeof AuthenticatedJobSeekerRecommendedJobsRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/resumes': {
      id: '/_authenticated/job-seeker/resumes'
      path: '/resumes'
      fullPath: '/job-seeker/resumes'
      preLoaderRoute: typeof AuthenticatedJobSeekerResumesRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/saved-jobs': {
      id: '/_authenticated/job-seeker/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/job-seeker/saved-jobs'
      preLoaderRoute: typeof AuthenticatedJobSeekerSavedJobsRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/job-seeker/settings': {
      id: '/_authenticated/job-seeker/settings'
      path: '/settings'
      fullPath: '/job-seeker/settings'
      preLoaderRoute: typeof AuthenticatedJobSeekerSettingsRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/jobs/$jobId_/apply': {
      id: '/jobs/$jobId_/apply'
      path: '/jobs/$jobId/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/companies_/$companyId': {
      id: '/_authenticated/admin/companies_/$companyId'
      path: '/companies/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports_/$reportId': {
      id: '/_authenticated/admin/reports_/$reportId'
      path: '/reports/$reportId'
      fullPath: '/admin/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedAdminReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users_/$userId': {
      id: '/_authenticated/admin/users_/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/employer/applications_/$applicationId': {
      id: '/_authenticated/employer/applications_/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/employer/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedEmployerApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/candidates_/$candidateId': {
      id: '/_authenticated/employer/candidates_/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/employer/candidates/$candidateId'
      preLoaderRoute: typeof AuthenticatedEmployerCandidatesCandidateIdRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/jobs/': {
      id: '/_authenticated/employer/jobs/'
      path: '/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof AuthenticatedEmployerJobsIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/job-seeker/applications_/$applicationId': {
      id: '/_authenticated/job-seeker/applications_/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/job-seeker/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedJobSeekerApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedJobSeekerRouteRoute
    }
    '/_authenticated/employer/jobs/$jobId/edit': {
      id: '/_authenticated/employer/jobs/$jobId/edit'
      path: '/jobs/$jobId/edit'
      fullPath: '/employer/jobs/$jobId/edit'
      preLoaderRoute: typeof AuthenticatedEmployerJobsJobIdEditRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/jobs/$jobId_/matches': {
      id: '/_authenticated/employer/jobs/$jobId_/matches'
      path: '/jobs/$jobId/matches'
      fullPath: '/employer/jobs/$jobId/matches'
      preLoaderRoute: typeof AuthenticatedEmployerJobsJobIdMatchesRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
    '/_authenticated/employer/jobs/$jobId_/pipeline': {
      id: '/_authenticated/employer/jobs/$jobId_/pipeline'
      path: '/jobs/$jobId/pipeline'
      fullPath: '/employer/jobs/$jobId/pipeline'
      preLoaderRoute: typeof AuthenticatedEmployerJobsJobIdPipelineRouteImport
      parentRoute: typeof AuthenticatedEmployerRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCompaniesCompanyIdRoute: typeof AuthenticatedAdminCompaniesCompanyIdRoute
  AuthenticatedAdminReportsReportIdRoute: typeof AuthenticatedAdminReportsReportIdRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
    AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
    AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
    AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCompaniesCompanyIdRoute:
      AuthenticatedAdminCompaniesCompanyIdRoute,
    AuthenticatedAdminReportsReportIdRoute:
      AuthenticatedAdminReportsReportIdRoute,
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedEmployerRouteRouteChildren {
  AuthenticatedEmployerApplicationsRoute: typeof AuthenticatedEmployerApplicationsRoute
  AuthenticatedEmployerCandidatesRoute: typeof AuthenticatedEmployerCandidatesRoute
  AuthenticatedEmployerCompanyRoute: typeof AuthenticatedEmployerCompanyRoute
  AuthenticatedEmployerInterviewsRoute: typeof AuthenticatedEmployerInterviewsRoute
  AuthenticatedEmployerMessagesRoute: typeof AuthenticatedEmployerMessagesRoute
  AuthenticatedEmployerNotificationsRoute: typeof AuthenticatedEmployerNotificationsRoute
  AuthenticatedEmployerPostJobRoute: typeof AuthenticatedEmployerPostJobRoute
  AuthenticatedEmployerSettingsRoute: typeof AuthenticatedEmployerSettingsRoute
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
  AuthenticatedEmployerApplicationsApplicationIdRoute: typeof AuthenticatedEmployerApplicationsApplicationIdRoute
  AuthenticatedEmployerCandidatesCandidateIdRoute: typeof AuthenticatedEmployerCandidatesCandidateIdRoute
  AuthenticatedEmployerJobsIndexRoute: typeof AuthenticatedEmployerJobsIndexRoute
  AuthenticatedEmployerJobsJobIdEditRoute: typeof AuthenticatedEmployerJobsJobIdEditRoute
  AuthenticatedEmployerJobsJobIdMatchesRoute: typeof AuthenticatedEmployerJobsJobIdMatchesRoute
  AuthenticatedEmployerJobsJobIdPipelineRoute: typeof AuthenticatedEmployerJobsJobIdPipelineRoute
}

const AuthenticatedEmployerRouteRouteChildren: AuthenticatedEmployerRouteRouteChildren =
  {
    AuthenticatedEmployerApplicationsRoute:
      AuthenticatedEmployerApplicationsRoute,
    AuthenticatedEmployerCandidatesRoute: AuthenticatedEmployerCandidatesRoute,
    AuthenticatedEmployerCompanyRoute: AuthenticatedEmployerCompanyRoute,
    AuthenticatedEmployerInterviewsRoute: AuthenticatedEmployerInterviewsRoute,
    AuthenticatedEmployerMessagesRoute: AuthenticatedEmployerMessagesRoute,
    AuthenticatedEmployerNotificationsRoute:
      AuthenticatedEmployerNotificationsRoute,
    AuthenticatedEmployerPostJobRoute: AuthenticatedEmployerPostJobRoute,
    AuthenticatedEmployerSettingsRoute: AuthenticatedEmployerSettingsRoute,
    AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
    AuthenticatedEmployerApplicationsApplicationIdRoute:
      AuthenticatedEmployerApplicationsApplicationIdRoute,
    AuthenticatedEmployerCandidatesCandidateIdRoute:
      AuthenticatedEmployerCandidatesCandidateIdRoute,
    AuthenticatedEmployerJobsIndexRoute: AuthenticatedEmployerJobsIndexRoute,
    AuthenticatedEmployerJobsJobIdEditRoute:
      AuthenticatedEmployerJobsJobIdEditRoute,
    AuthenticatedEmployerJobsJobIdMatchesRoute:
      AuthenticatedEmployerJobsJobIdMatchesRoute,
    AuthenticatedEmployerJobsJobIdPipelineRoute:
      AuthenticatedEmployerJobsJobIdPipelineRoute,
  }

const AuthenticatedEmployerRouteRouteWithChildren =
  AuthenticatedEmployerRouteRoute._addFileChildren(
    AuthenticatedEmployerRouteRouteChildren,
  )

interface AuthenticatedJobSeekerRouteRouteChildren {
  AuthenticatedJobSeekerApplicationsRoute: typeof AuthenticatedJobSeekerApplicationsRoute
  AuthenticatedJobSeekerInterviewsRoute: typeof AuthenticatedJobSeekerInterviewsRoute
  AuthenticatedJobSeekerMessagesRoute: typeof AuthenticatedJobSeekerMessagesRoute
  AuthenticatedJobSeekerNotificationsRoute: typeof AuthenticatedJobSeekerNotificationsRoute
  AuthenticatedJobSeekerProfileRoute: typeof AuthenticatedJobSeekerProfileRoute
  AuthenticatedJobSeekerRecommendedJobsRoute: typeof AuthenticatedJobSeekerRecommendedJobsRoute
  AuthenticatedJobSeekerResumesRoute: typeof AuthenticatedJobSeekerResumesRoute
  AuthenticatedJobSeekerSavedJobsRoute: typeof AuthenticatedJobSeekerSavedJobsRoute
  AuthenticatedJobSeekerSettingsRoute: typeof AuthenticatedJobSeekerSettingsRoute
  AuthenticatedJobSeekerIndexRoute: typeof AuthenticatedJobSeekerIndexRoute
  AuthenticatedJobSeekerApplicationsApplicationIdRoute: typeof AuthenticatedJobSeekerApplicationsApplicationIdRoute
}

const AuthenticatedJobSeekerRouteRouteChildren: AuthenticatedJobSeekerRouteRouteChildren =
  {
    AuthenticatedJobSeekerApplicationsRoute:
      AuthenticatedJobSeekerApplicationsRoute,
    AuthenticatedJobSeekerInterviewsRoute:
      AuthenticatedJobSeekerInterviewsRoute,
    AuthenticatedJobSeekerMessagesRoute: AuthenticatedJobSeekerMessagesRoute,
    AuthenticatedJobSeekerNotificationsRoute:
      AuthenticatedJobSeekerNotificationsRoute,
    AuthenticatedJobSeekerProfileRoute: AuthenticatedJobSeekerProfileRoute,
    AuthenticatedJobSeekerRecommendedJobsRoute:
      AuthenticatedJobSeekerRecommendedJobsRoute,
    AuthenticatedJobSeekerResumesRoute: AuthenticatedJobSeekerResumesRoute,
    AuthenticatedJobSeekerSavedJobsRoute: AuthenticatedJobSeekerSavedJobsRoute,
    AuthenticatedJobSeekerSettingsRoute: AuthenticatedJobSeekerSettingsRoute,
    AuthenticatedJobSeekerIndexRoute: AuthenticatedJobSeekerIndexRoute,
    AuthenticatedJobSeekerApplicationsApplicationIdRoute:
      AuthenticatedJobSeekerApplicationsApplicationIdRoute,
  }

const AuthenticatedJobSeekerRouteRouteWithChildren =
  AuthenticatedJobSeekerRouteRoute._addFileChildren(
    AuthenticatedJobSeekerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedEmployerRouteRoute: typeof AuthenticatedEmployerRouteRouteWithChildren
  AuthenticatedJobSeekerRouteRoute: typeof AuthenticatedJobSeekerRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedEmployerRouteRoute: AuthenticatedEmployerRouteRouteWithChildren,
  AuthenticatedJobSeekerRouteRoute:
    AuthenticatedJobSeekerRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CareerResourcesRoute: CareerResourcesRoute,
  ContactRoute: ContactRoute,
  EmployerRoute: EmployerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobSeekerRoute: JobSeekerRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  CompaniesCompanySlugRoute: CompaniesCompanySlugRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
